# Generated by Django 4.1.3 on 2022-11-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_title', models.CharField(max_length=200)),
                ('business_news', models.URLField(blank=True, null=True)),
                ('business_url', models.TextField()),
            ],
        ),
    ]
