# Generated by Django 4.1.3 on 2022-11-22 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_businessnews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessnews',
            old_name='business_news',
            new_name='business_image',
        ),
    ]
