# Generated by Django 4.1.3 on 2022-11-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_business_news_businessnews_business_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_title', models.CharField(max_length=200)),
                ('world_image', models.URLField(blank=True, null=True)),
                ('world_url', models.TextField()),
            ],
        ),
    ]
