# Generated by Django 4.1.3 on 2022-11-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_worldnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticsNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politics_title', models.CharField(max_length=200)),
                ('politics_image', models.URLField(blank=True, null=True)),
                ('politics_url', models.TextField()),
            ],
        ),
    ]
